In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.model_selection import train_test_split ,GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore")

In [20]:
df = pd.read_csv('final_features_dataset.csv')
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115
0,0.752,0.125333,2.016,29.692642,0.139026,27.058826,30.152409,32.765076,5.706249,124.894028,...,0.020475,0.010724,-0.014146,-0.026553,-0.036702,-0.029755,0.022368,-0.018264,0.003408,0.0
1,3.376,0.562667,1.216,28.902164,0.059650,27.226685,29.087835,30.215212,2.988527,161.266479,...,-0.028341,-0.039130,0.014202,-0.033629,-0.014142,0.016071,0.000418,0.052529,-0.027881,0.0
2,0.096,0.016000,2.000,33.309326,0.076475,30.667349,33.532410,35.704662,5.037313,75.671303,...,-0.052840,0.037898,-0.033048,0.016960,-0.029433,-0.049945,0.017078,-0.002990,0.013806,0.0
3,0.976,0.162667,1.536,31.678345,0.147221,30.229443,31.792450,33.827995,3.598553,183.706635,...,0.025264,-0.010136,0.017654,-0.041070,0.026746,0.013381,0.023744,-0.023588,0.021052,0.0
4,0.064,0.010667,0.832,19.091696,0.122966,18.151205,19.343756,20.891975,2.740770,146.654404,...,-0.003401,0.004876,-0.027515,-0.022376,-0.001362,0.055101,-0.002135,0.036428,0.041027,1.0

In [21]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115
count,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,...,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000,772.000000
mean,0.848497,0.141416,1.280055,26.875057,0.143425,24.111455,26.610576,29.572100,5.460645,176.706317,...,-0.005100,0.001908,0.014698,-0.019653,-0.004015,-0.007167,0.008198,-0.003111,0.007189,0.455959
std,1.053311,0.175552,1.246480,4.461412,0.075871,4.867895,4.664027,4.968869,3.664713,163.297135,...,0.032984,0.026521,0.027969,0.032181,0.029064,0.025377,0.026062,0.026269,0.028103,0.498379
min,0.000000,0.000000,0.000000,15.230464,0.009925,12.310999,12.693930,15.680657,0.821445,0.000000,...,-0.114870,-0.093372,-0.074318,-0.132130,-0.082997,-0.084960,-0.065482,-0.082023,-0.075397,0.000000
25%,0.000000,0.000000,0.000000,23.827170,0.094402,21.060303,23.454350,25.902406,3.283834,80.423510,...,-0.026838,-0.014627,-0.003926,-0.041131,-0.023928,-0.024674,-0.007982,-0.020221,-0.010867,0.000000
50%,0.512000,0.085333,1.148000,26.334584,0.120286,23.693402,26.207404,29.125484,4.342189,137.703613,...,-0.003823,0.001666,0.014396,-0.019878,-0.005290,-0.007313,0.008074,-0.002151,0.006701,0.000000
75%,1.248000,0.208000,1.856000,30.482754,0.172079,28.018923,30.537734,32.973633,6.285551,211.049927,...,0.016842,0.020118,0.033377,0.000848,0.015266,0.009744,0.025403,0.014146,0.026267,1.000000
max,5.008000,0.834667,5.728000,40.523838,0.471783,38.912983,39.263222,54.032879,24.687458,1284.285767,...,0.093574,0.097440,0.096453,0.085304,0.085877,0.069286,0.082380,0.067032,0.088328,1.000000

In [22]:
df.rename(columns= {'1115' : 'Label'}, inplace=True)

In [23]:
x = df.drop(['Label'] , axis = 1)
y = df['Label']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [38]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [35]:
param_grid = {
    'xg_boost':{
        'model' : xgb.XGBClassifier(use_label_encoder=False, eval_metric="logloss"),
        'params' : {
            'n_estimators': [200, 300],
            'max_depth': [3, 5, 7],
            'learning_rate': [0.01, 0.05, 0.1],
        },
    },
    'random_forest':{
            'model' : RandomForestClassifier(),
            'params' : {
                'n_estimators': [100, 200],
                'max_depth': [None, 10, 20],
                'min_samples_split': [2, 5],
            }
        },
        'svm':{
            'model' : SVC(),
            'params' : {
                'C': [0.1, 1, 10],
                'kernel': ['linear', 'rbf'],
                'gamma': ['scale', 'auto'],
            }
        }
}

In [ ]:
for model_name, mp in param_grid.items():
    clf = GridSearchCV(
        mp['model'], mp['params'], cv=5, n_jobs=-1, scoring='accuracy'
    )
    
    # scale only for SVM
    if model_name == "svm":
        clf.fit(x_train_scaled, y_train)
        y_pred = clf.predict(x_test_scaled)
    else:
        clf.fit(x_train, y_train)
        y_pred = clf.predict(x_test)

    print(f"Best parameters for {model_name}: {clf.best_params_}")
    print(f"cross-validation accuracy for {model_name}: {clf.best_score_}")
    print(f"test accuracy for {model_name}: {accuracy_score(y_test, y_pred)}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print("\n")

Best parameters for xg_boost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 300}
cross-validation accuracy for xg_boost: 0.9303566745344872
test accuracy for xg_boost: 0.9290322580645162
              precision    recall  f1-score   support

         0.0       0.94      0.95      0.94        95
         1.0       0.92      0.90      0.91        60

    accuracy                           0.93       155
   macro avg       0.93      0.92      0.92       155
weighted avg       0.93      0.93      0.93       155

[[90  5]
 [ 6 54]]


Best parameters for random_forest: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
cross-validation accuracy for random_forest: 0.9173485444531865
test accuracy for random_forest: 0.9354838709677419
              precision    recall  f1-score   support

         0.0       0.93      0.97      0.95        95
         1.0       0.95      0.88      0.91        60

    accuracy                           0.94       155
   macro avg       0.94      0.93      0.93       155
weighted avg       0.94      0.94      0.94       155

[[92  3]
 [ 7 53]]


Best parameters for svm: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
cross-validation accuracy for svm: 0.923865722528193
test accuracy for svm: 0.9354838709677419
              precision    recall  f1-score   support

         0.0       0.95      0.95      0.95        95
         1.0       0.92      0.92      0.92        60

    accuracy                           0.94       155
   macro avg       0.93      0.93      0.93       155
weighted avg       0.94      0.94      0.94       155

[[90  5]
 [ 5 55]]

Both Random Forest and SVM showed similar accuracy. However, I selected SVM because it produced fewer false negatives, meaning it has a higher recall for dementia cases.

In [41]:
svm = SVC(C = 10 , gamma='scale' , kernel='rbf')
svm.fit(x_train_scaled , y_train)
y_pred_svm = svm.predict(x_test_scaled)
print("SVM Test Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))

SVM Test Accuracy: 0.9354838709677419
              precision    recall  f1-score   support

         0.0       0.95      0.95      0.95        95
         1.0       0.92      0.92      0.92        60

    accuracy                           0.94       155
   macro avg       0.93      0.93      0.93       155
weighted avg       0.94      0.94      0.94       155

[[90  5]
 [ 5 55]]

In [43]:
from sklearn.pipeline import make_pipeline
import joblib
pipeline = make_pipeline(
    scaler, 
    svm)
joblib.dump(pipeline, 'pipeline.pkl')

['pipeline.pkl']